<script lang="ts">
	import Seo from '$lib/seo/Seo.svelte';
	import JsonLd from '$lib/seo/JsonLd.svelte';
	import { graph, breadcrumb } from '$lib/seo/schema';
	import SiteHeader from '$lib/SiteHeader.svelte';
	import SiteFooter from '$lib/SiteFooter.svelte';

	// Logo variants generated by `bun run brand` (scripts/brand/generate-logos.sh).
	const LOGO_SIZES = [512, 1024, 2048];
	const LOGOS = [
		{ id: 'black', label: 'Ink', note: 'for light backgrounds', dark: false },
		{ id: 'white', label: 'White', note: 'for dark backgrounds', dark: true },
		{ id: 'amber', label: 'Amber', note: 'accent — use sparingly', dark: true }
	];

	const ICONS = [
		{ id: 'cream', label: 'Ink on cream' },
		{ id: 'black', label: 'White on ink' },
		{ id: 'amber', label: 'Ink on amber' },
		{ id: 'white', label: 'Ink on white' }
	];

	const COVERS = [
		{ file: 'waterhouse-cover-1500x500.png', label: 'X / Twitter header', dims: '1500 × 500' },
		{ file: 'waterhouse-cover-1584x396.png', label: 'LinkedIn banner', dims: '1584 × 396' },
		{ file: 'waterhouse-cover-3000x1000.png', label: 'Hi-res master', dims: '3000 × 1000' }
	];

	const COLORS = [
		{ name: 'Cream', hex: '#FAF6F6', role: 'background', dark: false },
		{ name: 'Ink', hex: '#111111', role: 'type & lines', dark: true },
		{ name: 'Amber', hex: '#FF8C1A', role: 'accent / LED', dark: false },
		{ name: 'Amber Glow', hex: '#FFB55A', role: 'highlight', dark: false }
	];

	const OG_CARDS = [
		{ file: 'og.png', label: 'Home' },
		{ file: 'og/studios.png', label: 'Studios' },
		{ file: 'og/ateliers.png', label: 'Ateliers' },
		{ file: 'og/residency.png', label: 'Residency' },
		{ file: 'og/radio.png', label: 'Radio' },
		{ file: 'og/events.png', label: 'Events' },
		{ file: 'og/about.png', label: 'About' },
		{ file: 'og/faq.png', label: 'FAQ' },
		{ file: 'og/contact.png', label: 'Contact' },
		{ file: 'og/mediakit.png', label: 'Media kit' }
	];

	const PHOTOS = [
		{ file: 'banner.jpg', label: 'Waterhouse banner' },
		{ file: 'gallery/studio_front.jpg', label: 'Studio — front' },
		{ file: 'gallery/studio_back.jpg', label: 'Studio — back' },
		{ file: 'gallery/studio_1.jpg', label: 'Studio session' },
		{ file: 'gallery/event_1.jpg', label: 'Event 1' },
		{ file: 'gallery/event_2.jpg', label: 'Event 2' },
		{ file: 'gallery/event_3.jpg', label: 'Event 3' },
		{ file: 'gallery/gallery_1.jpg', label: 'Space 1' },
		{ file: 'gallery/gallery_2.jpg', label: 'Space 2' }
	];

	let copied = $state('');
	async function copyHex(hex: string) {
		await navigator.clipboard.writeText(hex);
		copied = hex;
		setTimeout(() => (copied = ''), 1500);
	}

	const dl = (file: string) => file.split('/').pop();
</script>

<Seo
	title="Media Kit — logos, covers & brand assets"
	image="/og/mediakit.png"
	description="Download Waterhouse Studios brand assets: the logo in SVG and PNG at every size, avatar tiles, social cover images, brand colors, typography and press photos."
/>
<JsonLd schema={graph(breadcrumb([{ name: 'Media Kit', path: '/mediakit' }]))} />

<SiteHeader />

<main class="bg-primary text-secondary font-jersey min-h-screen">
	<div class="container mx-auto max-w-5xl px-4 py-12">
		<nav class="mb-6 text-sm opacity-60" aria-label="Breadcrumb">
			<a href="/" class="hover:text-amber underline">Home</a> / Media Kit
		</nav>

		<!-- Hero: hardware panel -->
		<header class="panel mb-14 overflow-hidden rounded-3xl">
			<div class="strip border-b-2 border-black/15">
				<span class="flex items-center gap-3">
					<span class="led" aria-hidden="true"></span>
					WATERHOUSE · PRESS
				</span>
				<span class="hidden sm:inline">AMSTERDAM</span>
			</div>
			<div class="px-8 py-12 md:px-14 md:py-16">
				<h1 class="mb-3 text-6xl leading-none md:text-8xl">Media Kit</h1>
				<p class="text-amber max-w-xl text-2xl leading-tight md:text-3xl">
					Logos, covers, colors & photos — everything you need to feature Waterhouse Studios, one
					click away.
				</p>
			</div>
			<div class="strip border-t-2 border-black/15 text-[13px]">
				<span>MADE IN AMSTERDAM</span>
				<span class="hidden sm:inline">24·BIT · 96 kHz</span>
				<span>waterhousestudios.nl</span>
			</div>
		</header>

		<!-- Logo -->
		<section class="mb-16">
			<h2 class="section-title"><span class="led-sq" aria-hidden="true"></span>Logo</h2>
			<p class="mb-6 max-w-2xl text-lg opacity-70">
				The mark comes in three colorways. SVG is the master file; PNGs are pre-rendered on a
				transparent background at three widths.
			</p>
			<div class="grid gap-6 md:grid-cols-3">
				{#each LOGOS as logo (logo.id)}
					<div class="panel flex flex-col rounded-2xl p-4">
						<div
							class="mb-4 flex h-44 items-center justify-center rounded-lg border-2 border-black {logo.dark
								? 'checker-dark'
								: 'checker-light'}"
						>
							<img
								src="/brand/waterhouse-logo-{logo.id}.svg"
								alt="Waterhouse logo — {logo.label}"
								class="h-auto w-36"
								loading="lazy"
							/>
						</div>
						<div class="mb-1 flex items-baseline justify-between">
							<h3 class="text-2xl">{logo.label}</h3>
							<span class="text-sm opacity-50">{logo.note}</span>
						</div>
						<div class="mt-3 flex flex-wrap gap-2">
							<a
								href="/brand/waterhouse-logo-{logo.id}.svg"
								download={`waterhouse-logo-${logo.id}.svg`}
								class="chip chip-amber">SVG</a
							>
							{#each LOGO_SIZES as size (size)}
								<a
									href="/brand/waterhouse-logo-{logo.id}-{size}.png"
									download={`waterhouse-logo-${logo.id}-${size}.png`}
									class="chip">PNG {size}</a
								>
							{/each}
						</div>
					</div>
				{/each}
			</div>
		</section>

		<!-- Avatar tiles -->
		<section class="mb-16">
			<h2 class="section-title"><span class="led-sq" aria-hidden="true"></span>Avatar tiles</h2>
			<p class="mb-6 max-w-2xl text-lg opacity-70">
				Square, pre-padded versions for profile pictures, playlists and app icons. Round cropping is
				safe.
			</p>
			<div class="grid grid-cols-2 gap-6 md:grid-cols-4">
				{#each ICONS as icon (icon.id)}
					<div class="panel flex flex-col rounded-2xl p-3">
						<img
							src="/brand/waterhouse-icon-{icon.id}-512.png"
							alt="Waterhouse avatar tile — {icon.label}"
							class="mb-3 w-full rounded-lg border-2 border-black"
							loading="lazy"
						/>
						<span class="mb-2 text-lg leading-tight">{icon.label}</span>
						<div class="flex gap-2">
							<a
								href="/brand/waterhouse-icon-{icon.id}-512.png"
								download={`waterhouse-icon-${icon.id}-512.png`}
								class="chip">512</a
							>
							<a
								href="/brand/waterhouse-icon-{icon.id}-1024.png"
								download={`waterhouse-icon-${icon.id}-1024.png`}
								class="chip">1024</a
							>
						</div>
					</div>
				{/each}
			</div>
		</section>

		<!-- Cover / header -->
		<section class="mb-16">
			<h2 class="section-title"><span class="led-sq" aria-hidden="true"></span>Cover photo</h2>
			<p class="mb-6 max-w-2xl text-lg opacity-70">
				A ready-made header for social profiles, newsletters and press pages, in the Waterhouse
				hardware-panel style.
			</p>
			<div class="panel rounded-2xl p-4">
				<img
					src="/brand/waterhouse-cover-1500x500.png"
					alt="Waterhouse Studios cover — hardware panel with logo and tagline"
					class="mb-4 w-full rounded-lg border-2 border-black"
					loading="lazy"
				/>
				<div class="flex flex-wrap gap-2">
					{#each COVERS as cover (cover.file)}
						<a href="/brand/{cover.file}" download={cover.file} class="chip">
							{cover.label} · {cover.dims}
						</a>
					{/each}
				</div>
			</div>
		</section>

		<!-- SVG vs PNG -->
		<section class="mb-16">
			<h2 class="section-title"><span class="led-sq" aria-hidden="true"></span>SVG or PNG?</h2>
			<div class="grid gap-6 md:grid-cols-2">
				<div class="panel rounded-2xl p-6">
					<h3 class="mb-2 text-3xl">SVG <span class="text-amber text-xl">vector</span></h3>
					<p class="text-lg leading-snug opacity-80">
						An SVG describes the logo as mathematical shapes, so it stays razor-sharp at any size —
						a business card or a building wrap — and the file is tiny. Use it for print, websites,
						and any design tool (Figma, Illustrator, Canva).
					</p>
				</div>
				<div class="panel rounded-2xl p-6">
					<h3 class="mb-2 text-3xl">PNG <span class="text-amber text-xl">pixels</span></h3>
					<p class="text-lg leading-snug opacity-80">
						A PNG is a fixed grid of pixels with a transparent background. It works everywhere —
						slides, documents, social posts, video editors — but blurs if scaled past its size. Pick
						the width that's at least as large as you need.
					</p>
				</div>
			</div>
			<p class="strip mt-4 rounded-lg border-2 border-black bg-white text-sm">
				<span>RULE OF THUMB</span>
				<span class="tracking-normal normal-case"
					>SVG when a tool accepts it · PNG everywhere else</span
				>
			</p>
		</section>

		<!-- Colors -->
		<section class="mb-16">
			<h2 class="section-title"><span class="led-sq" aria-hidden="true"></span>Colors</h2>
			<p class="mb-6 max-w-2xl text-lg opacity-70">Click a swatch to copy its hex code.</p>
			<div class="grid grid-cols-2 gap-6 md:grid-cols-4">
				{#each COLORS as color (color.hex)}
					<button
						type="button"
						onclick={() => copyHex(color.hex)}
						class="panel cursor-pointer rounded-2xl p-3 text-left transition-transform hover:-translate-y-1"
					>
						<span
							class="mb-3 flex h-24 items-end rounded-lg border-2 border-black p-2 text-sm {color.dark
								? 'text-white'
								: 'text-black'}"
							style="background-color: {color.hex}"
						>
							{copied === color.hex ? 'COPIED ✓' : color.hex}
						</span>
						<span class="block text-xl leading-none">{color.name}</span>
						<span class="text-sm opacity-50">{color.role}</span>
					</button>
				{/each}
			</div>
		</section>

		<!-- Typography -->
		<section class="mb-16">
			<h2 class="section-title"><span class="led-sq" aria-hidden="true"></span>Typography</h2>
			<div class="panel rounded-2xl p-6 md:p-8">
				<div class="mb-4 flex flex-wrap items-baseline justify-between gap-2">
					<h3 class="text-3xl">Jersey 15</h3>
					<span class="text-sm opacity-50">display & body · free on Google Fonts</span>
				</div>
				<div class="rounded-lg border-2 border-black bg-black p-6 text-white">
					<p class="mb-2 text-4xl md:text-5xl">Waterhouse Studios</p>
					<p class="text-amber mb-4 text-2xl">The quick brown fox jumps over the lazy dog</p>
					<p class="text-lg tracking-widest opacity-70">ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789</p>
				</div>
				<a
					href="https://fonts.google.com/specimen/Jersey+15"
					target="_blank"
					rel="noopener noreferrer"
					class="chip chip-amber mt-4 inline-flex"
				>
					Get Jersey 15 on Google Fonts ↗
				</a>
			</div>
		</section>

		<!-- Social cards -->
		<section class="mb-16">
			<h2 class="section-title"><span class="led-sq" aria-hidden="true"></span>Social cards</h2>
			<p class="mb-6 max-w-2xl text-lg opacity-70">
				The link-preview cards used across the site (1200 × 630) — handy when sharing or embedding a
				Waterhouse page.
			</p>
			<div class="grid grid-cols-2 gap-4 md:grid-cols-3">
				{#each OG_CARDS as card (card.file)}
					<a
						href="/{card.file}"
						download={dl(card.file)}
						class="panel group rounded-xl p-2 transition-transform hover:-translate-y-1"
					>
						<img
							src="/{card.file}"
							alt="Social card — {card.label}"
							class="mb-2 w-full rounded-md border-2 border-black"
							loading="lazy"
						/>
						<span class="flex items-center justify-between px-1 text-lg">
							{card.label}
							<span class="text-amber opacity-0 transition-opacity group-hover:opacity-100">↓</span>
						</span>
					</a>
				{/each}
			</div>
		</section>

		<!-- Photos -->
		<section class="mb-16">
			<h2 class="section-title"><span class="led-sq" aria-hidden="true"></span>Photos</h2>
			<p class="mb-6 max-w-2xl text-lg opacity-70">
				High-resolution photos of the space, free to use in press coverage of Waterhouse Studios.
			</p>
			<div class="grid grid-cols-2 gap-4 md:grid-cols-3">
				{#each PHOTOS as photo (photo.file)}
					<a
						href="/{photo.file}"
						download={dl(photo.file)}
						class="panel group rounded-xl p-2 transition-transform hover:-translate-y-1"
					>
						<img
							src="/{photo.file}"
							alt="Waterhouse Studios — {photo.label}"
							class="mb-2 aspect-[4/3] w-full rounded-md border-2 border-black object-cover"
							loading="lazy"
						/>
						<span class="flex items-center justify-between px-1 text-lg">
							{photo.label}
							<span class="text-amber opacity-0 transition-opacity group-hover:opacity-100">↓</span>
						</span>
					</a>
				{/each}
			</div>
		</section>

		<!-- Usage -->
		<section>
			<h2 class="section-title"><span class="led-sq" aria-hidden="true"></span>House rules</h2>
			<div class="panel rounded-2xl p-6 text-lg leading-relaxed">
				<ul class="list-inside space-y-1">
					<li>· Give the logo clear space — about the height of its doorway on all sides.</li>
					<li>· Stick to the three colorways; don't recolor, outline, stretch or add effects.</li>
					<li>· On busy photos, place the logo on a cream, ink or amber tile first.</li>
					<li>
						· Questions or something missing? <a
							href="mailto:info@waterhousestudios.nl"
							class="text-amber underline">info@waterhousestudios.nl</a
						>
					</li>
				</ul>
			</div>
		</section>
	</div>
</main>

<SiteFooter />

<style>
	/* Hardware panel: hard border, warm gradient face, offset shadow. */
	.panel {
		border: 2px solid black;
		background-image: linear-gradient(180deg, #ffffff 0%, #efece6 100%);
		box-shadow: 8px 8px 0 black;
	}

	/* Brand strip: the letter-spaced serial rows on the hero panel. */
	.strip {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 1rem;
		padding: 0.65rem 1.5rem;
		font-size: 0.85rem;
		letter-spacing: 0.35em;
		color: rgba(0, 0, 0, 0.56);
	}

	/* Amber power LED (round on the hero, square on section titles). */
	.led {
		width: 0.8rem;
		height: 0.8rem;
		border-radius: 999px;
		background: var(--color-amber);
		box-shadow: 0 0 10px var(--color-amber);
	}
	.led-sq {
		width: 0.7rem;
		height: 0.7rem;
		border-radius: 2px;
		background: var(--color-amber);
		box-shadow: 0 0 8px var(--color-amber);
	}

	.section-title {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		margin-bottom: 0.75rem;
		font-size: 2.25rem;
		line-height: 1;
	}

	/* Download chips: mini midi-style buttons. */
	.chip {
		display: inline-flex;
		align-items: center;
		gap: 0.35rem;
		padding: 0.3rem 0.8rem;
		border: 2px solid black;
		border-radius: 0.5rem;
		background: white;
		font-size: 0.95rem;
		box-shadow: 3px 3px 0 black;
		transition: all 0.12s ease;
	}
	.chip:hover {
		transform: translate(-2px, -2px);
		box-shadow: 5px 5px 0 black;
	}
	.chip:active {
		transform: translate(2px, 2px);
		box-shadow: 0 0 0 black;
	}
	.chip-amber {
		background: var(--color-amber);
	}

	/* Transparency checkerboards behind the logo previews. */
	.checker-light {
		background-color: #f6f2ec;
		background-image:
			repeating-linear-gradient(
				45deg,
				#e7e1d6 25%,
				transparent 25%,
				transparent 75%,
				#e7e1d6 75%,
				#e7e1d6
			),
			repeating-linear-gradient(45deg, #e7e1d6 25%, #f6f2ec 25%, #f6f2ec 75%, #e7e1d6 75%, #e7e1d6);
		background-position:
			0 0,
			10px 10px;
		background-size: 20px 20px;
	}
	.checker-dark {
		background-color: #16161a;
		background-image:
			repeating-linear-gradient(
				45deg,
				#24242a 25%,
				transparent 25%,
				transparent 75%,
				#24242a 75%,
				#24242a
			),
			repeating-linear-gradient(45deg, #24242a 25%, #16161a 25%, #16161a 75%, #24242a 75%, #24242a);
		background-position:
			0 0,
			10px 10px;
		background-size: 20px 20px;
	}
</style>
